config/routes.rb
Rails.application.routes.draw do
  get '/users/profile', to: 'users#profile', as: 'user_profile'
  patch '/users/:id/avatar', to: 'users#update_avatar', as: 'user_avatar'
  get '/profile', to: 'users#profile', as: 'profile'
  get 'comments/create'
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :posts do
    resources :comments
  end
  resources :tasks
  resources :likes, only: [:create, :destroy]

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :replies, class_name: 'Comment', foreign_key: 'parent_comment_id', dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy
  belongs_to :parent_comment, class_name: 'Comment', optional: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likable, polymorphic: true
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_many_attached :images

  has_many :comments
  has_many :likes, as: :likable, dependent: :destroy

  belongs_to :user
  validates :title, presence: true

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  attribute :title, :string
  attribute :description, :string
  attribute :completed_at, :datetime
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :tasks
  has_many :likes, dependent: :destroy
  has_one_attached :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username])
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:like, :unlike]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params.merge(user: current_user))
    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_path(@post), notice: 'Comment created successfully.' }
        format.js # Render create.js.erb for AJAX response
      end
    else
      respond_to do |format|
        format.html { redirect_to post_path(@post), alert: 'Comment creation failed.' }
        format.js # Render create.js.erb for AJAX response
      end
    end
  end

  def like
    comment = Comment.find(params[:id])
    like_count = comment.likes.count

    render json: { success: true, likeCount: like_count }
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index      
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def show
      @post = Post.find(params[:id])
    end

    def create
      likable_type = params[:likable_type]
      likable_id = params[:likable_id]
      @likable = likable_type.constantize.find(likable_id)
      @like = @likable.likes.find_or_initialize_by(user: current_user)
  
      if @like.persisted?
        @like.destroy
        liked = false
      else
        @like.save
        liked = true
      end
  
      render json: { liked: liked }
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:create, :destroy]
    before_action :set_post, only: [:show, :destroy_like, :like, :unlike]

  
    def index
      @posts = Post.all
    end
    
    def create
      @post = current_user.posts.build(post_params)
      if @post.save
        redirect_to root_path, notice: 'Post created successfully.'
      else
        redirect_to root_path, alert: 'Post creation failed.'
      end
    end
  
    def edit
      @post = Post.find(params[:id])
    end

    def show
      @post = Post.find(params[:id])
      @comments = @post.comments
    end

    def destroy
      @post = current_user.posts.find(params[:id])
      @post.destroy
      redirect_to posts_path, notice: 'Post deleted successfully.'
    end
  
    
    def like
      @post = Post.find(params[:id])
      @post.likes.create(user_id: current_user.id)
      @post.increment!(:likes_count)
    
      redirect_to @post
    end
        
    def destroy_like
      @post = Post.find(params[:id])
      @like = Like.find_by(user_id: current_user.id, post_id: @post.id)
      @like.destroy
      redirect_to @post
    end

    private
  
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, images: [])
    end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def create
        super do |resource|
          resource.username = params[:user][:username]
          flash[:notice] = I18n.t('devise.registrations.signed_up', username: resource.username)
        end
    end
    
    protected
  
    def after_sign_up_path_for(resource)
      user_path(resource)
    end
  
    def after_update_path_for(resource)
      user_path(resource)
    end
  end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]
  
    def index
      @tasks = Task.all
    end
  
    def new
      @task = Task.new
    end
  
    def create
      @task = current_user.tasks.build(task_params)
      if @task.save
        redirect_to tasks_path, notice: 'Task created successfully.'
      else
        render :new
      end
    end
  
    def edit
      @task = Task.find(params[:id])
    end
  
    def update
      if @task.update(task_params)
        redirect_to tasks_path, notice: 'Task updated successfully.'
      else
        render :edit
      end
    end
  
    def destroy
      @task.destroy
      redirect_to tasks_path, notice: 'Task deleted successfully.'
    end
  
    private
  
    def set_task
      @task = Task.find(params[:id])
    end
  
    def task_params
      params.require(:task).permit(:title, :description, :completed_at)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def profile
      @user = current_user
    end

    def update_avatar
      @user = User.find(params[:id])
      @user.avatar.attach(params[:user][:avatar])
      redirect_to user_profile_path, notice: 'Avatar uploaded successfully.'
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_comment.html.erb
<%= comment.content %>
<!-- comments/show.html.erb -->
<%= render @comments %>

<script>
  // JavaScript code for handling the like functionality
  document.addEventListener('DOMContentLoaded', () => {
    const likeButtons = document.querySelectorAll('.like-button');

    likeButtons.forEach((button) => {
      button.addEventListener('click', (event) => {
        event.preventDefault();
        const commentId = event.target.dataset.commentId;

        // Send an AJAX request to the server to handle the like functionality
        fetch(`/comments/${commentId}/like`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': '<%= form_authenticity_token.to_s %>'
          },
          body: JSON.stringify({ comment: { like: true } })
        })
          .then(response => response.json())
          .then(data => {
            // Handle the response and update the UI accordingly
            if (data.success) {
              // Update the UI to reflect the updated like count or any other changes
              const likeCountElement = document.querySelector(`.comment-like-count-${commentId}`);
              likeCountElement.textContent = data.likeCount;
            }
          })
          .catch(error => console.error(error));
      });
    });
  });
</script>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.js.erb
$('#comments').append('<p><%= j render @comment %></p>');

app/views/home/index.html.erb
<%= link_to 'Profile', profile_path %>
<hr>
<% if user_signed_in? %>
  <%= form_for(Post.new, url: posts_path) do |form| %>
    <%= form.label :title %>
    <br>
    <%= form.text_field :title, placeholder: 'Enter your post title' %>
    <br>
    <%= form.label :content %>
    <br>
    <%= form.text_area :content, placeholder: 'Enter your post content' %>
    <br>
    <%= form.file_field :images, multiple: true %>
    <br>
    <%= form.submit 'Create Post' %>
  <% end %>
<% end %>
<hr>
<%= link_to 'Go to Posts', posts_path %>
<hr>
<%= link_to 'Tasks', tasks_path %>
<br>
<%= link_to 'New Task', new_task_path %>
<hr>
<% if user_signed_in? %>
  <%= form_tag destroy_user_session_path, method: :delete do %>
    <%= submit_tag 'Sign Out' %>
  <% end %>
<% else %>
  <%= link_to 'Register', new_user_registration_path %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>GunplaHub</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
h1,h2,h3,h4,h5,h6 {font-family: "Oswald"}
body {font-family: "Open Sans"}
</style>
</head>
<body class="w3-light-grey">

<!-- Navigation bar with social media icons -->
<div class="w3-bar w3-black w3-hide-small">
  <a href="/users/sign_in" class="w3-bar-item w3-button">Login</a>
  <a href="/profile" class="w3-bar-item w3-button">Profile</a>
  <a href="/posts" class="w3-bar-item w3-button">Posts</a>
  <a href="/tasks" class="w3-bar-item w3-button">Tasks</a>
  <% if user_signed_in? %>
    <a href="<%= destroy_user_session_path %>" class="w3-bar-item w3-button w3-right" data-method="delete">Sign Out</a>
  <% end %>
</div>
  
<!-- w3-content defines a container for fixed size centered content, 
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1600px">

  <!-- Header -->
  <header class="w3-container w3-center w3-padding-48 w3-white">
    <h1 class="w3-xxxlarge"><b>GunplaHub</b></h1>
    <h6>Welcome to the world of <span class="w3-tag">Gunpla</span></h6>
  </header>

  <!-- Image header -->
  <header class="w3-display-container w3-wide" id="home">
    <img class="w3-image" src="<%= image_path('Desk.png') %>" alt="Ver.Ka" width="1600" height="1060">
    <div class="w3-display-left w3-padding-large">
      <h1 class="w3-text-white">Sbhboi's</h1>
      <h1 class="w3-jumbo w3-text-white w3-hide-small"><b>GUNPLA HUB</b></h1>
      <h6><a href="/" class="w3-button w3-white w3-padding-large w3-large w3-opacity w3-hover-opacity-off">Go Home</a></h6>
    </div>
  </header>

  <!-- Grid -->
  <div class="w3-row w3-padding w3-border">
    <%= flash[:error] %> 
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>

    <script>
      // Toggle between hiding and showing blog replies/comments
      document.getElementById("myBtn").click();
      function myFunction(id) {
        var x = document.getElementById(id);
        if (x.className.indexOf("w3-show") == -1) {
          x.className += " w3-show";
        } else {
          x.className = x.className.replace(" w3-show", "");
        }
      }
      
      function likeFunction(x) {
        x.style.fontWeight = "bold";
        x.innerHTML = "✓ Liked";
      }

      function toggleComments() {
      var commentSection = document.getElementById("commentSection");
      if (commentSection.style.display === "none") {
        commentSection.style.display = "block";
      } else {
        commentSection.style.display = "none";
      }
      }

      $('.w3-button').on('click', function() {
      var button = $(this);
      var isLiked = button.data('liked');

      if (isLiked) {
        // Unlike functionality
        button.data('liked', false);
        button.html('<b><i class="fa fa-thumbs-up"></i> Like</b>');
      } else {
        // Like functionality
        button.data('liked', true);
        button.html('<b><i class="fa fa-thumbs-up"></i> Liked</b>');
      }
      });
      </script>
  </div>
  <!-- END GRID -->

</div>
<!-- END w3-content -->

<!-- Footer -->
<footer class="w3-container w3-dark-grey" style="padding:32px">
  <a href="#" class="w3-button w3-black w3-padding-large w3-margin-bottom"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">CSS by w3, Edited by Yours Truly.</a></p>
</footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form.file_field :images, multiple: true %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for(@post) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <%= f.submit 'Update Post' %>
<% end %>

app/views/posts/index.html.erb
<div class="post-container">
  <h1>All Posts</h1>
  <% @posts.each do |post| %>
    <div class="post-title">
      <%= link_to post.title, post_path(post), class: "post-link" %>
    </div>
  <% end %>
</div>
  
<hr>
<%= link_to 'Go to Home', root_path %>

app/views/posts/like.js.erb
// Update the like count element with the new count
$("#like-count-<%= @post.id %>").text("<%= @post.likes.count %>");

app/views/posts/show.html.erb
<div class="w3-container w3-white w3-margin w3-padding-large">
  <div class="w3-center">
    <h3><%= @post.title %></h3>
    <h5>Title description, <span class="w3-opacity"><%= @post.created_at.strftime("%B %d, %Y") %></span></h5>
  </div>

  <div class="w3-justify">
    <% if @post.image.attached? %>
      <%= image_tag @post.image.variant(resize_to_limit: [650, 400]) %>
    <% else %>
      <p>No image available</p>
    <% end %>

    <p><%= @post.content %></p>
    <p class="w3-left">
      <button class="w3-button w3-white w3-border" onclick="likeFunction(this)" data-likable-type="Post" data-likable-id="<%= @post.id %>">
        <b><i class="fa fa-thumbs-up"></i> Like</b>
      </button>
    </p>
    <p class="w3-right">
      <button class="w3-button w3-black" onclick="toggleComments()">
        <b>Replies </b> <span class="w3-tag w3-white"><%= @comments.count %></span>
          <div id="commentSection" style="display: none;">
            <% @comments.each do |comment| %>
              <div class="w3-row w3-margin-bottom">
                <div class="w3-col l2 m3">
                  <% if comment.user.avatar.attached? && comment.user.avatar.persisted? %>
                    <%= image_tag comment.user.avatar, style: "width:50px;" %>
                  <% else %>
                    <%= image_tag "no_avatar.png", style: "width:50px;" %>
                  <% end %>
                </div>
                <div class="w3-col l10 m9">
                  <h4><%= comment.user.username %></h4>
                  <p><%= simple_format(comment.content) %></p>
                </div>
              </div>
            <% end %>
          </div>
        </span>
      </button>
    </p>
    <p class="w3-clear"></p>

    <h2>Add a Comment</h2>
      <%= form_for([@post, @post.comments.build]) do |f| %>
        <%= f.text_area :content, placeholder: 'Write a comment...' %>
        <br>
        <%= f.submit 'Post Comment' %>
      <% end %>
  </div>
</div>
<hr>
<%= link_to 'Go to Home', root_path %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_with model: @task, url: task_path(@task), method: :patch do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :completed_at %>
    <%= form.date_field :completed_at %>
  </div>

  <%= form.submit 'Update Task' %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<% @tasks.each do |task| %>
  <div class="task">
    <% if task.user.avatar.attached? %>
      <%= image_tag task.user.avatar, size: "50x50" %>
    <% else %>
      <%= image_tag "no_avatar.png", width: "50", height: "50" %>
    <% end %>
    <div class="task-content">
      <h3><%= task.title %></h3>
      <p><%= task.description %></p>
      <p>Due Date: <%= task.completed_at %></p>
      <br>
      <%= link_to 'Edit', edit_task_path(task) %>
      <%= form_with model: task, method: :delete, data: { confirm: 'Are you sure you want to delete this task?' } do |f| %>
        <%= f.submit 'Delete' %>
      <% end %>
    </div>
  </div>
<% end %>

<%= link_to 'New Task', new_task_path %>
<hr>
<%= link_to 'Go to Home', root_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @task, url: tasks_path do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :completed_at %>
    <%= form.date_field :completed_at %>
  </div>

  <%= form.submit 'Create Task' %>
<% end %>

app/views/users/profile.html.erb
<h1>Profile</h1>

<h2>User Information</h2>
<p>Username: <%= @user.username %></p>
<p>Email: <%= @user.email %></p>

<h2>Avatar</h2>
<%= image_tag @user.avatar if @user.avatar.attached? %>
<%= form_with(model: @user, url: user_avatar_path(@user), method: :patch, local: true) do |form| %>
  <%= form.file_field :avatar %>
  <%= form.submit 'Upload Avatar' %>
<% end %>
<hr>
<h2>Post History</h2>
<% @user.posts.each do |post| %>
  <h3><%= post.title %></h3>
  <p><%= post.content %></p>
<% end %>
<hr>
<h2>Comment History</h2>
<% @user.comments.each do |comment| %>
  <p><%= comment.content %></p>
<% end %>
<%= link_to 'Go to Home', root_path %>